[theme]
# Color primario de elmentos interactivos
primaryColor = "#00569e"

# Color de fondo para el area principal
backgroundColor = "#ffffff"

# Color de fondo para el sidebar y elementos interactivos
secondaryBackgroundColor = "#f3f3f3"

# Color para textos
textColor = "#000000"

font = "serif"

[client]
toolbarMode = "viewer"